version: '3.7'

services:
  wazuh:
    image: wazuh/wazuh-odfe:4.2.6
    container_name: wazuh
    hostname: wazuh
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_agentless:/var/ossec/agentless
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: wazuh/wazuh-kibana-odfe:4.2.6
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - 443:5601
    environment:
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/opendistroforelasticsearch.example.org.cert
      - SERVER_SSL_KEY=/usr/share/kibana/config/opendistroforelasticsearch.example.org.key

    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    
  ubuntu1:
    image: ubuntu:latest
    container_name: ubuntu1
    hostname: ubuntu1
    command: >
      /bin/bash -c "\
      apt-get update && \
      apt-get install -y net-tools curl gpg systemctl && \
      curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
      gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && \
      chmod 644 /usr/share/keyrings/wazuh.gpg && \
      echo 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main' | \
      tee -a /etc/apt/sources.list.d/wazuh.list && \
      apt-get update && \
      tail -f /dev/null"


  #ubuntu2:
  #  image: ubuntu:latest
  #  container_name: ubuntu2
  #  hostname: ubuntu2
  #  command: >
  #    /bin/bash -c "\
  #    apt-get update && \
  #    apt-get install -y net-tools curl gpg systemctl && \
  #    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
  #    gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && \
  #    chmod 644 /usr/share/keyrings/wazuh.gpg && \
  #    echo 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main' | \
  #    tee -a /etc/apt/sources.list.d/wazuh.list && \
  #    apt-get update && \
  #    tail -f /dev/null"
  
  debian1:
    image: debian:latest
    container_name: debian1
    hostname: debian1
    command: >
      /bin/bash -c "\
      apt-get update && \
      apt-get install -y net-tools curl gpg systemctl && \
      curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
      gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && \
      chmod 644 /usr/share/keyrings/wazuh.gpg && \
      echo 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main' | \
      tee -a /etc/apt/sources.list.d/wazuh.list && \
      apt-get update && \
      tail -f /dev/null"
  
  #debian2:
  #  image: debian:latest
  #  container_name: debian2
  #  hostname: debian2
  #  command: >
  #    /bin/bash -c "\
  #    apt-get update && \
  #    apt-get install -y net-tools curl gpg systemctl && \
  #    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
  #    gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && \
  #    chmod 644 /usr/share/keyrings/wazuh.gpg && \
  #    echo 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main' | \
  #    tee -a /etc/apt/sources.list.d/wazuh.list && \
  #    apt-get update && \
  #    tail -f /dev/null"

volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_agentless:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:
